version: '3'

services:
  php7:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.5
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8080:80"